### ISSUE TITLE
Cannot use utils from this package as a dependency in other package

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-compiler#31]
Basically you cannot do something like that:

```js
const { utils: compilerUtils } = require( '@ckeditor/ckeditor5-dev-compiler' )( /* config * / );
```

because the `ckeditor5-dev-compiler` module requires a config object which shall contain the `MODULE_DIR` property (which should be an object).

If you don't pass the config object, this module throws an error:

```
/Users/pomek/Projects/cksource/ckeditor5-dev-docs/node_modules/@ckeditor/ckeditor5-dev-compiler/lib/compiler/index.js:37
        for ( let format in config.MODULE_DIR ) {
                                  ^

TypeError: Cannot read property 'MODULE_DIR' of undefined
    at module.exports (/Users/pomek/Projects/cksource/ckeditor5-dev-docs/node_modules/@ckeditor/ckeditor5-dev-compiler/lib/compiler/index.js:37:28)
```

[This part of  code](https://github.com/ckeditor/ckeditor5-dev-compiler/blob/master/lib/compiler/index.js#L37) could be protected against invalid config value.

**Comment by Reinmar** [comment]
It's a matter of calling the exported function with the right arguments. I don't see a problem with this as along as this function is properly documented. So we don't need a protection – the thrown error is obvious enough. I also see that there's a proper documentation, so for me it's enough.

PS. We can improve configuring those packages, because right now it's a bit cumbersome and ugly. But that's for another ticket.
